### ISSUE TITLE
Push docker images to docker hub

### ISSUE THREAD

**Issue by benjefferies** [OpenBankingToolkit/openbanking-reference-implementation#22]
## Story

As a developer using the openbanking toolkit, I want to consume the docker images so that I can run a local environment.

Benefits;

Don't need an auth token to be able to use `docker-compose up` and have it pull docker images.
Moving away from codefresh is a win from a reliability and cost perspective. 

## Acceptance criteria

- docker images published to docker hub

### Release Notes

Affected App: X

Description: X
<end release notes>

**Comment by benjefferies** [comment]
https://github.com/OpenBankingToolkit/consumer-data-right-reference-implementation/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed addressed some of these

**Comment by BohoCode** [comment]
Images are now pushed to Google Container Registry (gcr).
