### ISSUE TITLE
Registration disabled (psu and tpp)

### ISSUE THREAD

**Issue by jorgesanchezperez** [OpenBankingToolkit/openbanking-reference-implementation#234]
**Registration disabled**

External Issue Id: 50014
Date Raised: 22/05/2020

Description of the bug
Unable to register a PSU user as registration is disabled.
>UI Message: Registration disabled

On the following endpoint:
https://auth.*******.forgerock.financial/register?realm=openbanking

Investigation of the bug

**PR related to that change before deploy**:
- https://github.com/OpenBankingToolkit/openbanking-ui-common/pull/2/files

**Flag**
- https://github.com/ForgeCloud/ob-customers/blob/9826ca853cb7dd21813bde6b1708a0b46484abef/lloyds/deployment-settings.js#L10

**Source**
- https://github.com/OpenBankingToolkit/openbanking-ui-common/blob/6f651e0ff996b7949f84b266d728afad8ec4c528/projects/authentication/src/lib/components/forgerock-auth-login/forgerock-auth-login.component.ts#L40

Release Notes
Affected App: X

Description: X

**Comment by jorgesanchezperez** [comment]
The UI common implement a flag to disable the registration for tpp and psu users:
- `disableRegistration` for default is false.
> We need to find where is using that flag.

**Searching the UI pods using the ui-template chart label**
UI charts:
```bash
kubectl get services --show-labels | grep ui-template
```
Result list:
```bash
analytics-node
analytics-ui
auth
bank-ui 
directory-ui
manual-onboarding
swagger-ui 
tpp-node
tpp-ui
```
**Searching the flag `disableRegistration`**
Access bash UI pod:
```bash
kubectl exec -it `kubectl get pods --selector=app=${service-name-previous-list} -o name` sh
```
Finding the flag `disableRegistration` on pod: 
```bash
cat usr/share/nginx/html/deployment-settings.json
```

Flag: `disableRegistration` found in:
`lbg-sandbox-dev-green` version `3.1.2-queen-rc7`
- auth: `disableRegistration:true`
- bank-ui: `disableRegistration:true`

**Comment by jorgesanchezperez** [comment]
## Solution

1. Update the deployment-setting.json file from ${TEMPLATE} (`echo $TEMPLATE`)directly on the pod and restart the pod.
1. Update the file on ob-customers repo to still up to date for the next deployment.

**OR**
1. Update the deployment-setting.json file from ob-customers and deploy a new lloyds version.

**Comment by BohoCode** [comment]
Looks like a good analysis to me. @jgazeleyfr would probably prefer a fresh deployment rather than building up potential deployment problems?

**Comment by BohoCode** [comment]
This may not be an issue for the queen release... Hima has requested that 50014 be marked solved.

We should fix it in the ob-customers repo config though for the lbg dev/integ but NOT for pre-prod and production.

**Comment by BohoCode** [comment]
Have given Lloyds the above curl command to use to create PSU users in the cluster and they are happy with that and have requested that the initial ticket be marked as solved.
