### ISSUE TITLE
Cannot run the repository ,, says license.txt missing

### ISSUE THREAD

**Issue by Sairaj14** [OpenBankingToolkit/openbanking-reference-implementation#328]
[ERROR] Failed to execute goal com.mycila:license-maven-plugin:3.0:format (default) on project forgerock-openbanking-reference-implementation: Execution default of goal com.mycila:license-maven-plugin:3.0:format failed: Cannot read header document file://H:\LTI\backup\openbanking-reference-implementation-master/legal/LICENSE.txt. Cause: Resource file://H:\LTI\backup\openbanking-reference-implementation-master/legal/LICENSE.txt not found in file system, classpath or URL: H: Unknown host H -> [Help 1]

**Comment by jorgesanchezperez** [comment]
This file exist and you can found it in the proper folder.
Seems that you have any problem to mapping `H`.

**Comment by jorgesanchezperez** [comment]
@Sairaj14 can you give us an update about the issue?
